language: python
python:
- "3.5.3"
- "3.6"
#- "3.6-dev"
#- "3.7-dev"
- "pypy3.5"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install -r test_req.txt
script:
- py.test --verbose --cov=./aiochan
- codecov